using UnityEngine;
using Hospital;
using System.Collections;

public class HospitalTutorialStep : ScriptableObject
{
    public int StepID;
    public StepTag StepTag;             //this should be unique! One step tag can be assigned only to one step! Also step tag enums cannot be changed as this would break save/load
    public bool IsNonLinear;
    public int CoinsReward;
    public int ExperienceReward;
    public float StepInfoDelay;
    public float StepCameraDelay;
    public bool ForceCloseHovers;       //when entering the step all hovers will be closed
    public bool ForceClosePopups;       //when entering the step all popups will be closed
    public bool IsBehindUI;             //in some steps we want tutorial UI to be behind popups and hovers
    public string TutorialStepInfo;     //THIS IS NO LONGER USED! TEXTS ARE LOADED FROM LOCKIT! (I2Languages) This is left here just for easy step identification
    public bool NeedsOpenAnimation;
    public bool CloseAfterClick;
    public bool UseCameraTargeting;
    public string TargetMachineTag;
    public bool UseZooming;
    public float ZoomValue;
    public CameraTargetingType CameraTargetingType;
    public bool CameraLocked;
    public string CameraTargetRotatableObjectTag;
    public Vector3 CameraTargetVectorPosition;
    public Vector2 CameraTargetOffset = new Vector2(0, 0);
    public Vector3[] IndicatorPositions;
    public StepInfoType StepInfoType = StepInfoType.FullScreenPopup;
    public bool InGameTapToContinueShown = false;
    public bool TapToContinueHERE = false;
    public TutorialCharacter TutorialCharacter = TutorialCharacter.None;
    public Vector2 InGameCloudPos = new Vector2(0, 0);
    public float InGameCloudWidth = 480f;
    public TutorialAnimationClips TutorialAnimationClips = TutorialAnimationClips.None;
    public Condition NecessaryCondition = Condition.NoCondition;
    public NotificationType NotificationType = NotificationType.None;
    public HospitalTutorialStep NextStep;
    public bool isFreePlayStep = false;
    public bool forceShowObjectives = false;
    public AdditionalTutorialGraphic[] additionalGraphics = new AdditionalTutorialGraphic[0];

    public bool locksUIMainButtons = false;
    public SimpleUI.UIElement.UIElementType[] pointerVisibleOnPopups = null;

#if UNITY_EDITOR
    [UnityEditor.MenuItem("Assets/Create/HospitalTutorialStep")]
    public static void CreateAsset()
    {
        ScriptableObjectUtility.CreateAsset<HospitalTutorialStep>();
    }
#endif
}


public enum Condition
{
    NoCondition,
    ExpAmountChanged,
    HospitalNamed,
    SetCurrentlyPointedMachine,
    SetTutorialArrow,
    FinishedBuilding,
    DrawerOpened,
    FirstPatientArriving,
    PatientCardIsOpen,
    PatientCardIsClosed,
    RuntimeStepInfoChanged,
    Level2ReachedAndClosed,
    Level3ReachedAndClosed,
    Level4ReachedAndClosed,
    Level5ReachedAndClosed,
    Level6ReachedAndClosed,
    Level7ReachedAndClosed,
    Level8ReachedAndClosed,
    Level9ReachedAndClosed,
    Level10ReachedAndClosed,
    Level11ReachedAndClosedNonLinear,
    Level12ReachedAndClosed,
    Level13ReachedAndClosedNonLinear,
    Level18ReachedAndClosed,
    MoveRotateRoomEnd,
    NOTVALIDANYMORE_PharmacyIsOpen,
    DontUse_TreatmentRoomNotBuilt,
    ObjectDoesNotExistOnLevel,
    KidsRoomUnlocked,
    KidPatientSpawned,
    DontUse_XRayDummyRemoved,
    Level24ReachedAndClosed,
    Level14ReachedAndClosed,
    Level15ReachedAndClosed,
    Level16ReachedAndClosedNonLinear,
    Level23ReachedAndClosed,
    Level1ReachedAndClosed,
    FirstEmergencyPatientSpawned,
    SpawnFirstPatient,
    FirstPatientNearSignOfHospital,
    ExpandConditions,
    DiagnoseSpawn,
    NotEnoughPanacea,
    FollowBob,
    MedicopterTookOff,
    VIPLeoReachedPosition,
    TreasurePopUpOpened,
    Level17ReachedAndClosed,
    Level19ReachedAndClosedNonLinear,
    VIPMedicopterStarted,
    VIPReachedBed,
    VIPNotCured,
    HomeHospitalLoaded,
    PackageCollected,
    PatioNotCleared,
    WisePharmacyVisited,
    BoostersPopUpOpen,
    GiftReady,
    OpenWelcomePopUp,
    Level20ReachedAndClosedNonLinear,
    Level30ReachedAndClosedNonLinear,
    Level42ReachedAndClosedNonLinear,
    EpidemyCompleted,
    SecondDiagnosticMachineOpen,
    TenPatioDecorations,
    TwentyProbeTables,
    Level16ReachedAndClosed,
    EpidemyStarting,
    Level10NewspaperClosed,
    Level10Wise1Closed,
    TreasureCollected,
    BubbleBoyAvailable,
    VipFlyByStart,
    ShowDailyQuestAnimation,
    PushNotificationsDisabled,
    Level19ReachedAndClosed,
    Level20ReachedAndClosed,
    MicroscopeShow,
    Free,
    Level22ReachedAndClosedNonLinear,
    GlobalEventStarted,
    ExpAmountChangedNonLinear,
    LevelGoalsActive,
    OnFirstVitaminesMakerPopupOpened,
    VitaminesMakerEmma1Closed,
    MaternityReadyToBeUnlocked,
    VitaminesDeliverd,
    EpidemyCenterBuilt,
    DailyRewardPopupOpenedAutomatically,
    CuredVipCountIsEnough,
}

public enum NotificationType
{
    None,
    TutorialBegining,
    ShowTutorialsInputField,
    HideTutorialsInputField,
    SheetRemove,
    ObjectSelected,
    PanaceaCollected,
    BlueDoctorsOfficeAdded,
    BoughtWithDiamonds,
    BluePotionsCollected,
    ProductionStarted,
    ElixirDelivered,
    CollectableCollected,
    QueueExtended,
    StaticObjectUpgraded,
    NotvalidObjectAdded,
    ObjectMoved,
    ResourceAmountChanged,
    NotEnoughCurrency,
    LevelUp,
    DiamondUsed,
    PatientCured,
    Error,
    InGameEmmaHidden,
    ReceptionBuilt,
    DummyRemoved,
    DrawerOpened,
    FinishedBuilding,
    FirstEmergencyPatientReachedBed,
    FullscreenTutHidden,
    BlueSyrupCollected,
    PatientCardOpened,
    PatientCardClosed,
    SyrupLabBuildingStarted,
    TapAnywhere,
    SyrupLabAdded,
    MedicineExistInStorage,
    PatientCuredInPatientCard,
    YellowDoctorsOfficeAdded,
    MoveRotateRoomStartChanging,
    StepInfoClose,
    PharmacyOpened,
    PharmacyOffersClicked,
    PharmacyClosed,
    HospitalRoomsExpanded,
    GreenDoctorsOfficeAdded,
    KidsUIOpen,
    KidsUIClosed,
    KidArrivedToKidsRoom,
    ElixirMixerAdded,
    BlueSyrupProductionStarted,
    DoctorRewardCollected,
    PatientZeroPopUpOpened,
    PatientZeroPopUpClosed,
    AmbulanceReachedHospital,
    KidsClicked,
    WiseHospitalLoaded,
    VIPTeaseMedicopter,
    XRayAdded,
    BlueSyrupExtractionCompleted,
    TreasurePopUpClosed,
    EmergencyWardOpened,
    EmergencyWardClosed,
    DrawerClosed,
    VIPSpawned,
    PackageArrived,
    PackageClicked,
    PatioElementCleared,
    VipPopUpOpen,
    BoxPopUpOpen,
    PatioDecorationsAdded,
    DiagnosePatientInBed,
    CloseWelcomePopUp,
    NewspaperRewardDiamond,
    NewspaperRewardExp,
    EpidemyClicked,
    Level10NewspaperClosed,
    Level10Wise1Closed,
    Level10WiseGiveBooster,
    TreasureClicked,
    BubbleBoyClicked,
    VipFlyByEnd,
    DailyQuestPopUpClosed,
    DailyQuestPopUpOpen,
    MicroscopeGoodBacteriaAdded,
    MicroscopeClosed,
    BacteriaPatientInBed,
    OliviaLetterClosed,
    VitaminesMakerEmma1Closed,
    MaternityWardClicked,
    MaternityWardRenovate,
    MaternityWardBuildEnd,
    MaternityReadyToBeUnlocked,
    WaitingRoomBlueOrchidAdded,
    LaborRoomBlueOrchidAdded,
    MotherReachedWaitingRoom,
    WaitingRoomWorkingClicked,
    MailBoxPopupClosed,
    PackageText,
    PillMakerAdded,
    BoosterPopupClosed,
    ObjectivePanelOpened,
    ObjectivePanelClosed,
    PatientSentToXRay,
    FirstPlantPlanted,
    NotEnoughPanacea,
    PanaceaCollectorUpgraded,
    VipSpeedupPopupOpened,
    VipSpeedupPopupClosed,
    VIPPatientCured,
    VipUpgradeTutorial1Closed,
    VipUpgradeTutorial2Closed,
    VipUpgradeTutorial3Closed,
    VipUpgradeTutorial4Closed,
    VipSpeedup0Closed,
}

public enum TutorialAnimationClips
{
    None,
    BuildDoctor,
    ProbeTableCollect,
    ProbeTableSeed,
    DeliverElixirToDoctor,
    ProduceCures,
    MoveAndRotateObjects,
}

public enum StepInfoType
{
    FullScreenPopup,
    InGamePopup,
    TutorialAnimation,
    None
}

public enum TutorialCharacter
{
    None,
    Emma1,
    Emma2,
    Wise1,
    Wise2,
    BobWrite1,
    BobWrite2,
    Driver,
    Kid,
    Newspaper,
    VIP_LeoHealthy,
    VIP_LeoSick,
    BubbleBoy,
    BobBacteria,
    OliviaLetter
}


public enum CameraTargetingType
{
    None,
    TargetVector3Position,
    TargetRotatableObject,
    PatientDiagnosis
}


public enum StepTag
{
    None = 0,
    zero = 1,
    first_msg = 2,
    open_reception_action = 3,
    first_patient_spawn = 4,
    first_patient_follow = 5,
    build_doctor_text = 6,
    build_doctor_anim = 7,
    build_doctor_drawer = 8,
    build_doctor_finish = 9,
    build_doctor_unpack = 10,
    elixir_deliver_text_before = 11,
    elixir_deliver_anim = 12,
    elixir_deliver = 13,
    doctor_speed_up = 14,
    doctor_reward_text = 15,
    doctor_reward_collect = 16,
    patient_text_1 = 233,
    patient_text_2 = 17,
    name_hospital_open = 18,
    name_hospital_close = 19,
    patient_text_3 = 20,
    newspaper_1 = 21,
    lab_intro_big = 22,
    lab_intro_small = 23,
    lab_intro_text = 24,
    lab_collector_tap = 25,
    lab_collector_works = 234,
    lab_collector_info = 235,
    elixir_collect_anim = 236,
    elixir_collect_text = 26,
    elixir_seed_text_before = 27,
    elixir_seed_anim = 28,
    elixir_seed_text_after = 29,
    elixir_deliver_again_info = 30,
    elixir_deliver_again = 31,
    doctor_speed_up_again = 32,
    doctor_reward_again = 33,
    follow_ambulance = 34,
    bed_patient_arrived = 35,
    patient_card_open = 36,
    patient_card_text_1 = 37,
    patient_card_text_2 = 38,
    syrup_lab_build = 39,
    syrup_lab_unpack = 40,
    syrup_lab_elixirs_missing = 41,
    syrup_production_anim = 42,
    syrup_production_start = 43,
    syrup_in_production = 44,
    cure_bed_patient = 45,
    keep_curing_text_1 = 46,
    emma_on_george = 47,
    level_4 = 48,
    first_yellow_patient_popup_open = 49,
    yellow_doc_add = 50,
    yellow_doc_build = 51,
    yellow_doc_unpack = 52,
    yellow_doc_elixirs = 53,
    arrange_text_before = 54,
    arrange_anim = 55,
    arrange_text_after = 56,
    level_5 = 57,
    green_doc_add = 58,
    green_doc_build = 59,
    green_doc_unpack = 60,
    elixir_mixer_text = 61,
    new_probe_tables = 62,
    wise_1 = 63,
    wise_2 = 64,
    emma_about_wise = 65,
    blink_friends = 66,
    expand_text = 67,
    expand_arrow = 68,
    level_7 = 69,
    pharmacy_open = 70,
    pharmacy_offers = 71,
    pharmacy_close = 72,
    beds_room_text = 73,
    vip_tease_heli = 74,
    vip_tease_leo1 = 75,
    vip_tease_leo2 = 76,
    vip_tease_emma = 77,
    new_cures_1 = 78,
    new_cures_2 = 79,
    level_11 = 80,
    kids_arrow = 81,
    kids_talking = 82,
    kids_info = 83,
    kids_open = 84,
    kids_thanks = 85,
    kids_unlocked = 86,
    level_14 = 87,
    diagnose_spawn = 88,
    diagnose_open_patient_card = 89,
    diagnose_text = 90,
    diagnose_xray_add = 91,
    diagnose_xray_build = 92,
    diagnose_xray_unpack = 93,
    level_15 = 94,
    garden_text = 95,
    level_16 = 96,
    level_17 = 97,
    epidemy_newspaper = 98,
    epidemy_openpopup = 99,
    level_23 = 100,
    positive_energy_text = 101,
    level_3 = 102,
    syrup_production_done = 103,
    syrup_collect_text = 104,
    treasure_from_Leo = 105,
    DoesNotExist_keep_curing_text_2 = 106,
    syrup_lab_add = 107,
    level_6 = 108,
    green_doc_add_text = 109,
    first_green_patient_popup_open = 110,
    DoesNotExist_Emergency_Ward_Closed = 111,
    beds_room_text_again = 112,
    drawer_opened_for_beds = 113,
    drawer_opened_for_beds_again = 114,
    level_9 = 115,
    level_8 = 116,
    level_10 = 117,
    level_12 = 118,
    level_13 = 119,
    Vip_Room_Reminder = 120,
    Vip_Room_Unpack = 121,
    Vip_Leo_sick_heli = 122,
    Vip_Leo_Sick_1 = 123,
    Emma_on_Sick_Leo = 124,
    Close_Vip_Patient_Card = 125,
    Emma_on_VIP_Special_rewards = 126,
    newspaper_2 = 127,
    Wise_booster_1 = 128,
    Wise_booster_2 = 129,
    emma_on_Xray = 130,
    NotEnoughPanacea = 131,     //nonlinear tag
    wise_thank_you = 132,
    package_arrive = 133,
    package_click = 134,
    package_collected = 135,
    patio_tidy_1 = 136,
    patio_tidy_2 = 137,
    last_step = 138,
    package_emma = 139,
    kids_unlocked_2 = 140,
    wise_pharmacy = 141,
    diagnose_george = 142,
    beds_room_text_lvl6 = 143,
    beds_room_text_again_lvl6 = 144,
    drawer_opened_for_beds_lvl6 = 145,
    drawer_opened_for_beds_again_lvl6 = 146,
    blink_box_button = 147,
    patio_tidy_3 = 148,
    patio_tidy_4 = 149,
    patio_tidy_5 = 150,
    patio_tidy_6 = 151,
    NL_boosters = 152,     //nonlinear tag
    NL_gifts = 153,        //nonlinear tag
    NL_newspaper_lvl_11 = 154,
    NL_newspaper_lvl_13 = 155,
    NL_newspaper_lvl_16 = 156,    //removed, unused
    NL_newspaper_lvl_19 = 157,    //this was moved to level 22 but changing this tag may cause save issues
    NL_newspaper_lvl_20 = 158,
    NL_newspaper_lvl_30 = 159,
    NL_newspaper_lvl_42 = 160,
    NL_newspaper_diagnosis = 161,
    NL_newspaper_epidemy = 162,
    NL_newspaper_probe_tables = 163,
    NL_newspaper_patio_decos = 164,
    epidemy_emma = 165,
    epidemy_starting = 166,
    level_18 = 167,
    elixir_mixer_add = 168,
    kids_emma = 169,
    NL_newspaper_lvl_10 = 170,        //same step as old linear newspaper_2
    NL_lvl_10_wise_1 = 171,           //same step as old linear Wise_booster_1
    NL_lvl_10_wise_2 = 172,           //same step as old linear Wise_booster_2
    treasure_first_spawn = 173,
    treasure_arrow = 174,
    treasure_collected = 175,
    bubble_boy_intro = 176,
    bubble_boy_arrow = 177,
    bubble_boy_available = 178,
    vip_flyby_emma_1 = 179,
    vip_flyby = 180,
    vip_flyby_emma_2 = 181,
    daily_quests_unlocked = 182,
    daily_quests_popup_1 = 183,
    daily_quests_popup_2 = 184,
    NL_push_disabled = 185,
    daily_quests_button_arrow = 186,
    pharmacy_tap_to_open = 187,
    bacteria_newspaper = 188,
    bacteria_bob_1 = 189,
    bacteria_bob_2 = 190,
    bacteria_emma_18 = 191,
    level_19 = 192,
    bacteria_emma_micro_1 = 193,
    bacteria_emma_micro_2 = 194,
    bacteria_emma_micro_3 = 195,
    bacteria_emma_micro_4 = 196,
    bacteria_emma_micro_5 = 197,
    bacteria_george_1 = 198,
    bacteria_george_2 = 199,
    bacteria_george_3 = 200,
    bacteria_george_4 = 201,
    bacteria_george_5 = 202,
    bacteria_emma_end = 203,
    level_20 = 204,
    bacteria_spawn = 205,
    olivia_letter = 206,
    emma_on_olivia = 207,
    keep_curing_patients_l2 = 208,
    level_goals_ended = 209,
    NL_vitamines_maker_emma_1 = 210,
    NL_vitamines_maker_emma_2 = 211,

    maternity_ready_to_be_unlocked = 212,
    maternity_tap_to_open = 213,
    maternity_waiting_for_start_renew = 214,
    maternity_waiting_for_build_end = 215,
    maternity_waiting_for_open = 216,
    maternity_waiting_for_enter = 217,
    maternity_tutorial_ended = 218,

    maternity_welcome = 219,
    maternity_waiting_room_drawer_open = 220,
    maternity_waiting_room_finish = 221,
    maternity_waiting_room_unpack = 222,
    maternity_waiting_room_completed = 223,
    maternity_labor_room_into = 224,
    maternity_labor_room_drawer_open = 225,
    maternity_labor_room_finish = 226,
    maternity_labor_room_unpack = 227,
    maternity_labor_room_completed = 228,
    maternity_mother_in_bed = 229,
    maternity_waiting_for_labor_info_a = 230,
    maternity_waiting_for_labor_info_b = 231,
    maternity_scenario_a_ended = 232,
    // 233-236 are higher up
    objective_panel_closed = 237,
    elixir_seed_success = 238,
    yellow_doc_elixir_deliver = 239,
    vip_sign_tap = 240,
    vip_upgrade_info = 241,
    vip_tap_to_cure = 242,

    NL_vip_upgrade_1 = 243,
    NL_vip_upgrade_2 = 244,
    NL_vip_upgrade_3 = 245,
    NL_vip_upgrade_4 = 246,
    NL_vip_upgrade_5 = 247,

    vip_speedup_0 = 248,
    vip_speedup_1 = 249,
    vip_speedup_2 = 250,

    REPUTATION_BUTTON_TAP = 251,
    REPUTATION_INFO = 252,
    SKIP_TUTORIALS_TO_THIS_STEP = 253,
}